import todayDate from '../utils/dateFormater';

const propertiesData = [
  {
    id: 1,
    owner: 1,
    name: 'Kings Apartment',
    status: 'Available',
    price: 20000000,
    state: 'Delta',
    city: 'Warri',
    address: '9 Jakpa Road, Effurun',
    type: '3 bedroom',
    created_on: todayDate,
    image_url: 'https://res.cloudinary.com/property-pro-lite/image/upload/v1561326667/iiyxcceemy20eeincxlf.jpg',
    ownerEmail: 'ble@gmail.com',
    ownerPhoneNumber: '08167672019',
  },
  {
    id: 2,
    owner: 2,
    name: 'Gold Apartment',
    status: 'Available',
    price: 20000000,
    state: 'Delta',
    city: 'Warri',
    address: '9 Jakpa Road, Effurun',
    type: '3 bedroom',
    created_on: todayDate,
    image_url: 'https://res.cloudinary.com/property-pro-lite/image/upload/v1561326667/iiyxcceemy20eeincxlf.jpg',
    ownerEmail: 'ble@gmail.com',
    ownerPhoneNumber: '08167672019',
  },
  {
    id: 3,
    owner: 3,
    name: 'Kings Apartment',
    status: 'Available',
    price: 20000000,
    state: 'Delta',
    city: 'Warri',
    address: '9 Jakpa Road, Effurun',
    type: '2 bedroom',
    created_on: todayDate,
    image_url: 'https://res.cloudinary.com/property-pro-lite/image/upload/v1561326667/iiyxcceemy20eeincxlf.jpg',
    ownerEmail: 'ble@gmail.com',
    ownerPhoneNumber: '08167672019',
  },
  {
    id: 4,
    owner: 4,
    name: 'Gold Apartment',
    status: 'Available',
    price: 20000000,
    state: 'Delta',
    city: 'Warri',
    address: '9 Jakpa Road, Effurun',
    type: '2 bedroom',
    created_on: todayDate,
    image_url: 'https://res.cloudinary.com/property-pro-lite/image/upload/v1561326667/iiyxcceemy20eeincxlf.jpg',
    ownerEmail: 'ble@gmail.com',
    ownerPhoneNumber: '08167672019',
  },
  {
    id: 5,
    owner: 5,
    name: 'Diamond Apartment',
    status: 'Available',
    price: 20000000,
    state: 'Delta',
    city: 'Warri',
    address: '9 Jakpa Road, Effurun',
    type: '4 bedroom',
    created_on: todayDate,
    image_url: 'https://res.cloudinary.com/property-pro-lite/image/upload/v1561326667/iiyxcceemy20eeincxlf.jpg',
    ownerEmail: 'ble@gmail.com',
    ownerPhoneNumber: '08167672019',
  },
  {
    id: 6,
    owner: 6,
    name: 'Diamond Apartment',
    status: 'Available',
    price: 20000000,
    state: 'Delta',
    city: 'Warri',
    address: '9 Jakpa Road, Effurun',
    type: '4 bedroom',
    created_on: todayDate,
    image_url: 'https://res.cloudinary.com/property-pro-lite/image/upload/v1561326667/iiyxcceemy20eeincxlf.jpg',
    ownerEmail: 'ble@gmail.com',
    ownerPhoneNumber: '08167672019',
  },
  {
    id: 7,
    owner: 7,
    name: 'Diamond Apartment',
    status: 'Available',
    price: 20000000,
    state: 'Delta',
    city: 'Warri',
    address: '9 Jakpa Road, Effurun',
    type: 'mini flat',
    created_on: todayDate,
    image_url: 'https://res.cloudinary.com/property-pro-lite/image/upload/v1561326667/iiyxcceemy20eeincxlf.jpg',
    ownerEmail: 'ble@gmail.com',
    ownerPhoneNumber: '08167672019',
  },
  {
    id: 8,
    owner: 8,
    name: 'Diamond Apartment',
    status: 'Available',
    price: 20000000,
    state: 'Delta',
    city: 'Warri',
    address: '9 Jakpa Road, Effurun',
    type: 'mini flat',
    created_on: todayDate,
    image_url: 'https://res.cloudinary.com/property-pro-lite/image/upload/v1561326667/iiyxcceemy20eeincxlf.jpg',
    ownerEmail: 'ble@gmail.com',
    ownerPhoneNumber: '08167672019',
  },
];

export default propertiesData;
